### ISSUE TITLE
Consider don't use static variable

### ISSUE THREAD

**Issue by Riey** [djdisodo/glade-bindgen#1]
I think `new` method is enough

User can make thier own static anytime with favorite method like `thread_local` or `once_cell` or `lazy_static`... etc

Even some users like me just want use owned value

**Comment by djdisodo** [comment]
@Riey
thanks for your feedback!
I'll make `new()` method public so anyone can create owned value

currently it doesn't initiate static value till `get()` is called
so it only takes a very little space on memory

but I'll add way to disable static value like this if you want
`generate_bind_build_script<T: AsRef<Path>>(directory_path: T, static_value: bool)`

**Comment by Riey** [comment]
Optional static variable sounds great!

**Comment by djdisodo** [comment]
d8be8cb000de68f6aefa61228ce7eb6e291df4ae
added to version 0.2
